/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.grapenlp.core;

public class u_context {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected u_context(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(u_context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jgrapenlpJNI.delete_u_context(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public u_context(u_context_key_value_hasher the_hasher_) {
    this(jgrapenlpJNI.new_u_context(u_context_key_value_hasher.getCPtr(the_hasher_), the_hasher_), true);
  }

  public void ua_set(SWIGTYPE_p_unsigned_short key_begin, SWIGTYPE_p_unsigned_short key_end, SWIGTYPE_p_unsigned_short value_begin, SWIGTYPE_p_unsigned_short value_end) {
    jgrapenlpJNI.u_context_ua_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(key_begin), SWIGTYPE_p_unsigned_short.getCPtr(key_end), SWIGTYPE_p_unsigned_short.getCPtr(value_begin), SWIGTYPE_p_unsigned_short.getCPtr(value_end));
  }

}
